### ISSUE TITLE
NPE with gp-list for ACOSJ card

### ISSUE THREAD

**Issue by biafra23** [OpenJavaCard/openjavacard-tools#3]
GPLifeCycle.read() throws a NullPointerException when GPCard.transactPlainAndCheck() throws a SWException with code SW_REFERENCED_DATA_NOT_FOUND in GPCard.readData(). 

This happens to me with an ACOSJ card that can be read by `gp -l`

The error SW_REFERENCED_DATA_NOT_FOUND should not be hidden by an NPE. So for now I would also rethrow if data is not found. But how does gp -l read the listing on that card?

Would it help if I post the output of `gp - l -d -v` here?

**Comment by biafra23** [comment]
Apparently this card does not have a CPLC. 
`gp -i` reports: `No CPLC`

**Comment by promovicz** [comment]
First I would like a debug trace, if possible. Note that identifying information and keys might be included.

You can generate one by running the tool with "./run-trace.sh" instead of "./run.sh".

I will also gladly accept "gp" output for reference.

**Comment by promovicz** [comment]
I am actually interested in learning about the card, too.

Already looking for NPE fix.

**Comment by promovicz** [comment]
Should be fixed.

**Comment by biafra23** [comment]
```2 actionable tasks: 2 executed
[main] DEBUG org.openjavacard.gp.GPContext - findSingleCard()
[main] DEBUG org.openjavacard.gp.GPContext - findSingleTerminal()
[main] DEBUG org.openjavacard.gp.GPContext - findTerminals()
[main] TRACE org.openjavacard.gp.GPContext - checking terminal "ACS ACR1252 Dual Reader"
Host GP configuration:
  ISD auto
  Protocol policy SCP*
  Security policy CMAC

CONNECTING
[main] DEBUG org.openjavacard.gp.GPCard - connected T=1 ATR=3b89800141434f534a763130311a
[main] TRACE org.openjavacard.gp.GPCard - apdu > CLA=00 INS=a4 P12=0400 LC=08 DATA=a000000003000000
[main] TRACE org.openjavacard.gp.GPCard - apdu < SW=6a82 [file not found] (no data)
[main] TRACE org.openjavacard.gp.GPCard - apdu > CLA=00 INS=a4 P12=0400 LC=08 DATA=a000000151000000
[main] TRACE org.openjavacard.gp.GPCard - apdu < SW=9000 [no error] LE=94 DATA=6f5c8408a000000151000000a550734a06072a864886fc6b01600c060a2a864886fc6b02020201630906072a864886fc6b03640b06092a864886fc6b040255650b06092a864886fc6b020103660c060a2b060104012a026e01039f6501ff
[main] DEBUG org.openjavacard.gp.GPCard - found ISD at a000000151000000
[main] TRACE org.openjavacard.gp.GPCard - apdu > CLA=00 INS=a4 P12=0400 LC=08 DATA=a000000151000000
[main] TRACE org.openjavacard.gp.GPCard - apdu < SW=9000 [no error] LE=94 DATA=6f5c8408a000000151000000a550734a06072a864886fc6b01600c060a2a864886fc6b02020201630906072a864886fc6b03640b06092a864886fc6b040255650b06092a864886fc6b020103660c060a2b060104012a026e01039f6501ff
[main] DEBUG org.openjavacard.gp.GPCard - static keys:
keyset "GlobalPlatform" version 0:
 key MASTER cipher DES3 secret 404142434445464748494a4b4c4d4e4f
[main] DEBUG org.openjavacard.gp.GPCard - readCPLC()
[main] TRACE org.openjavacard.gp.GPCard - readData(9f7f)
[main] TRACE org.openjavacard.gp.GPCard - apdu > CLA=80 INS=ca P12=9f7f (no data)
[main] TRACE org.openjavacard.gp.GPCard - apdu < SW=6a88 [referenced data not found] (no data)
Exception in thread "main" java.lang.NullPointerException
	at org.openjavacard.gp.protocol.GPLifeCycle.read(GPLifeCycle.java:90)
	at org.openjavacard.gp.GPCard.readCPLC(GPCard.java:592)
	at org.openjavacard.gp.GPCard.connect(GPCard.java:396)
	at org.openjavacard.tool.command.GPCommand.run(GPCommand.java:143)
	at org.openjavacard.tool.Main.runCommand(Main.java:62)
	at org.openjavacard.tool.Main.execute(Main.java:55)
	at org.openjavacard.tool.Main.main(Main.java:100)```

**Comment by promovicz** [comment]
(Should have guessed that the trace is pretty short with this bug)

In any case I am always interested in trace-level output from fresh cards or any in fact that you can share.

**Comment by promovicz** [comment]
Does it work with the patch?

**Comment by biafra23** [comment]
BTW: To get any logging with the gradle build one needs to replace:
`compile group: 'org.slf4j', name: 'slf4j-jdk14', version: '1.7.25'`
with 
`compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'` in `build.gradle`.

**Comment by biafra23** [comment]
It is indeed fixed on master.
